### ISSUE TITLE
Search by topic

### ISSUE THREAD

**Issue by adambarthelson** [gkze/stars#1]
Would it be possible to add a search by topic, like it's done in Github Explore?

**Comment by gkze** [comment]
Looks like the [topics API is in beta since 2017](https://developer.github.com/changes/2017-07-17-update-topics-on-repositories/ - sounds doable. One possible solution would be to add a `Tags`/`Topics` field to the `Star` struct and index it with storm.

**Comment by gkze** [comment]
Fixed by https://github.com/gkze/stars/releases/tag/v0.2.0
